steps:
# build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         '_RAILS_MASTER_KEY=${_RAILS_MASTER_KEY}',
         '--build-arg',
         '_DOTENV=${_DOTENV}',
         '-t',
         '${_GCR_REGION}/${_GCR_PROJECT}/${_GCR_IMAGE_NAME}:${_GCR_TAG}',
         '--cache-from',
         '${_GCR_REGION}/${_GCR_PROJECT}/${_GCR_IMAGE_NAME}:${_GCR_TAG}',
         '.']

# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", '${_GCR_REGION}/${_GCR_PROJECT}/${_GCR_IMAGE_NAME}']

timeout: 3600s

substitutions:
  _GCR_REGION: asia.gcr.io
  _GCR_PROJECT: buzz-connection
  _GCR_IMAGE_NAME: user-app
  _GCR_TAG: latest
