steps:
# build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         '_RAILS_MASTER_KEY=${_RAILS_MASTER_KEY}',
         '--build-arg',
         '_DOTENV=${_DOTENV}',
         '-t',
         '${_IMAGE_NAME}:${_IMAGE_TAG}',
         '.']

# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", '${_IMAGE_NAME}:${_IMAGE_TAG}']

timeout: 3600s

substitutions:
  _IMAGE_NAME: asia.gcr.io/buzz-connection/user-app
  _IMAGE_TAG: $REVISION_ID
