development:
  adapter: redis
  url: <%= ENV.fetch("CABLE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: buzz_connection_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["CABLE_URL"] %>
  channel_prefix: buzz_connection_production
